In [5]:
'''

    190031554 -- SuryaTeja Koka
    
1. Data preparations in Data Science

I.
    (i) Create 2- One dimensional Arrays and print sum of individual element and multiply  each with 3
    (ii) Manipulate Logical and, OR Not operations on Array
    (iii) Perform data Slicing Operations
    (iv) Perform Boolean operations between arrays

II.  Create 2- Two dimensional Arrays and print sum of individual element and multiply  each with 3
    (v) Manipulate Logical and, OR Not operations on Array
    (vi) Perform data Slicing Operations
    (vii) Perform Boolean operations between arrays

III. reshape(), arrange(), resize(), hsplit(),Extract ones, Two’s in arrays, Scalar()

IV. Create Data Frame with a MultiIndex

V. import .CSV file do the following
(https://www.kaggle.com/aljarah/xAPI-Edu-Data- Students' Academic Performance Dataset)
1.describe()
2. Mean()
3. Median()
4. Slicing operations

'''


"\n1. Data preparations in Data Science\n\nI.\n    (i) Create 2- One dimensional Arrays and print sum of individual element and multiply  each with 3\n    (ii) Manipulate Logical and, OR Not operations on Array\n    (iii) Perform data Slicing Operations\n    (iv) Perform Boolean operations between arrays\n\nII.  Create 2- Two dimensional Arrays and print sum of individual element and multiply  each with 3\n    (v) Manipulate Logical and, OR Not operations on Array\n    (vi) Perform data Slicing Operations\n    (vii) Perform Boolean operations between arrays\n\nIII. reshape(), arrange(), resize(), hsplit(),Extract ones, Two’s in arrays, Scalar()\n\nIV. Create Data Frame with a MultiIndex\n\nV. import .CSV file do the following\n(https://www.kaggle.com/aljarah/xAPI-Edu-Data- Students' Academic Performance Dataset)\n1.describe()\n2. Mean()\n3. Median()\n4. Slicing operations\n\n"

In [29]:
import pandas as pd
import numpy as np

In [30]:
# Create 2-1D array
# Sub task - 1 (i)

a = [1,2,3,4,5]
b = [6,7,8,9,10]

ary_a = np.array(a)
ary_b = np.array(b)


In [31]:
# sum of individual elements

sum_array = ary_a+ary_b
print(sum_array)

[ 7  9 11 13 15]


In [32]:
# sum of the sum array

sum(sum_array)

55

In [33]:
# multiplying each and every element by 3

3 * sum_array

array([21, 27, 33, 39, 45])

In [34]:
# (ii) Manipulate Logical and, OR Not operations on Array
# Not Operator

np.logical_not(sum_array != 26)

array([False, False, False, False, False])

In [35]:
# And operator

np.logical_and(sum_array>20, sum_array<50)

array([False, False, False, False, False])

In [36]:
# OR operator

np.logical_and(sum_array>20, sum_array<50)

array([False, False, False, False, False])

In [51]:
# (iii) Perform data Slicing Operations

Slicing=np.array([1,2,3,4,5,6,7])
print(Slicing[1:3])


[2 3]


In [42]:
# (iv) Perform Boolean operations between arrays

test_score = np.array([[83,71,57,63],
                       [54,68,81,45]])

passing_score = test_score > 60
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [66]:
# II.  Create 2- Two dimensional Arrays and print sum of individual element and multiply  each with 3

array1 = np.array([(1,2,3),(4,5,6)])
array2 = np.array([(4,5,6),(1,2,3)])

array1
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
array1.shape

(2, 3)

In [89]:
array1 = np.array([(1,2,3),(4,5,6)])

array1


array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
# changes columns to rows and rows to columns
array1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
a = np.array([[1,2], [3,4]])
# filling empty spaces to make the data good or Return a new array with the specified shape.
np.resize(a,(3,2))

array([[1, 2],
       [3, 4],
       [1, 2]])

In [99]:
np.arange(1, 11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
# forming the suff and reshaping it using arange and reshape and then using hsplit() ---- Horizontal split to make data prepared example 
a = np.arange(16).reshape(4,4) 

print ('First array:' )
print (a) 
print ('\n' ) 

print ('Horizontal splitting:' )
b = np.hsplit(a,2) 
print (b) 
print ('\n')

First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Horizontal splitting:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]




In [110]:
# IV. Create Data Frame with a MultiIndex

# This is like declaring the dataframe and stuff... specifying values for each colomn
df = pd.DataFrame({"a" : [4,5,6],
                  "b" : [7,8,9],
                  "c" : [10,11,12]},
                 index = [1,2,3])
df

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [118]:
# multi indexing using a default function
df = pd.DataFrame({"a" : [4,5,6],
                  "b" : [7,8,9],
                  "c" : [10,11,12]},
                  index = pd.MultiIndex.from_tuples([('d',1),('d',2),('e',2)], names = ['n','v']))

df
    

a  b   c
n v          
d 1  4  7  10
  2  5  8  11
e 2  6  9  12

In [120]:
surya = pd.read_csv('file.csv')
surya

gender NationalITy PlaceofBirth       StageID GradeID SectionID  \
0        M          KW       KuwaIT    lowerlevel    G-04         A   
1        M          KW       KuwaIT    lowerlevel    G-04         A   
2        M          KW       KuwaIT    lowerlevel    G-04         A   
3        M          KW       KuwaIT    lowerlevel    G-04         A   
4        M          KW       KuwaIT    lowerlevel    G-04         A   
..     ...         ...          ...           ...     ...       ...   
475      F      Jordan       Jordan  MiddleSchool    G-08         A   
476      F      Jordan       Jordan  MiddleSchool    G-08         A   
477      F      Jordan       Jordan  MiddleSchool    G-08         A   
478      F      Jordan       Jordan  MiddleSchool    G-08         A   
479      F      Jordan       Jordan  MiddleSchool    G-08         A   

         Topic Semester Relation  raisedhands  VisITedResources  \
0           IT        F   Father           15                16   
1           IT        F   Father           20                20   
2           IT        F   Father           10                 7   
3           IT        F   Father           30                25   
4           IT        F   Father           40                50   
..         ...      ...      ...          ...               ...   
475  Chemistry        S   Father            5                 4   
476    Geology        F   Father           50                77   
477    Geology        S   Father           55                74   
478    History        F   Father           30                17   
479    History        S   Father           35                14   

     AnnouncementsView  Discussion ParentAnsweringSurvey  \
0                    2          20                   Yes   
1                    3          25                   Yes   
2                    0          30                    No   
3                    5          35                    No   
4                   12          50                    No   
..                 ...         ...                   ...   
475                  5           8                    No   
476                 14          28                    No   
477                 25          29                    No   
478                 14          57                    No   
479                 23          62                    No   

    ParentschoolSatisfaction StudentAbsenceDays Class  
0                       Good            Under-7     M  
1                       Good            Under-7     M  
2                        Bad            Above-7     L  
3                        Bad            Above-7     L  
4                        Bad            Above-7     M  
..                       ...                ...   ...  
475                      Bad            Above-7     L  
476                      Bad            Under-7     M  
477                      Bad            Under-7     M  
478                      Bad            Above-7     L  
479                      Bad            Above-7     L  

[480 rows x 17 columns]

In [123]:
# statistical data...

surya.describe()

raisedhands  VisITedResources  AnnouncementsView  Discussion
count   480.000000        480.000000         480.000000  480.000000
mean     46.775000         54.797917          37.918750   43.283333
std      30.779223         33.080007          26.611244   27.637735
min       0.000000          0.000000           0.000000    1.000000
25%      15.750000         20.000000          14.000000   20.000000
50%      50.000000         65.000000          33.000000   39.000000
75%      75.000000         84.000000          58.000000   70.000000
max     100.000000         99.000000          98.000000   99.000000

In [127]:
surya.mean()

raisedhands          46.775000
VisITedResources     54.797917
AnnouncementsView    37.918750
Discussion           43.283333
dtype: float64

In [128]:
surya.median()

raisedhands          50.0
VisITedResources     65.0
AnnouncementsView    33.0
Discussion           39.0
dtype: float64

In [134]:
somevar = slice(surya)
somevar

slice(None,     gender NationalITy PlaceofBirth       StageID GradeID SectionID  \
0        M          KW       KuwaIT    lowerlevel    G-04         A   
1        M          KW       KuwaIT    lowerlevel    G-04         A   
2        M          KW       KuwaIT    lowerlevel    G-04         A   
3        M          KW       KuwaIT    lowerlevel    G-04         A   
4        M          KW       KuwaIT    lowerlevel    G-04         A   
..     ...         ...          ...           ...     ...       ...   
475      F      Jordan       Jordan  MiddleSchool    G-08         A   
476      F      Jordan       Jordan  MiddleSchool    G-08         A   
477      F      Jordan       Jordan  MiddleSchool    G-08         A   
478      F      Jordan       Jordan  MiddleSchool    G-08         A   
479      F      Jordan       Jordan  MiddleSchool    G-08         A   

         Topic Semester Relation  raisedhands  VisITedResources  \
0           IT        F   Father           15                16   
1